export const activityUiMapping = [
  { page: 'Activity', section: 'Header', element: 'Activity score', sourcePaths: ['dailyActivity.score'], transform: 'toNumber', fallback: 'Not in this export', notes: 'Selected day score' },
  { page: 'Activity', section: 'Key metrics', element: 'Goal progress', sourcePaths: ['dailyActivity.totalCalories', 'dailyActivity.targetCalories'], transform: 'total/target * 100', fallback: 'Not available in this export', notes: 'Shows ratio and raw calories' },
  { page: 'Activity', section: 'Key metrics', element: 'Total burn', sourcePaths: ['dailyActivity.totalCalories'], transform: 'toNumber + cal', fallback: 'Not available in this export', notes: 'Daily calories burned' },
  { page: 'Activity', section: 'Key metrics', element: 'Activity time', sourcePaths: ['dailyActivity.mediumActivityTime', 'dailyActivity.highActivityTime'], transform: 'sum seconds -> h/m', fallback: 'Not available in this export', notes: 'Medium + high activity' },
  { page: 'Activity', section: 'Key metrics', element: 'Steps', sourcePaths: ['dailyActivity.steps'], transform: 'toNumber', fallback: 'Not available in this export', notes: 'Daily steps' },
  { page: 'Activity', section: 'Contributors', element: 'Stay active', sourcePaths: ['dailyActivity.sedentaryTime', 'dailyActivity.contributors.stay_active'], transform: 'seconds -> inactivity text + scoreBand', fallback: 'Not available yet', notes: 'Oura-like inactivity message' },
  { page: 'Activity', section: 'Contributors', element: 'Move every hour', sourcePaths: ['dailyActivity.inactivityAlerts', 'dailyActivity.contributors.move_every_hour'], transform: 'alerts count + scoreBand', fallback: 'Not available yet', notes: 'Alert count detail text' },
  { page: 'Activity', section: 'Contributors', element: 'Meet daily goals', sourcePaths: ['dailyActivity.metersToTarget', 'dailyActivity.contributors.meet_daily_targets'], transform: 'meters to target + scoreBand', fallback: 'Not available yet', notes: 'Uses meet_daily_targets/goals if present' },
  { page: 'Activity', section: 'Contributors', element: 'Training frequency', sourcePaths: ['dailyActivity.contributors.training_frequency'], transform: 'scoreBand(score)', fallback: 'Not available yet', notes: 'Label from contributor score' },
  { page: 'Activity', section: 'Contributors', element: 'Training volume', sourcePaths: ['dailyActivity.contributors.training_volume'], transform: 'scoreBand(score)', fallback: 'Not available yet', notes: 'Label from contributor score' },
  { page: 'Activity', section: 'Contributors', element: 'Recovery time', sourcePaths: ['dailyActivity.contributors.recovery_time'], transform: 'scoreBand(score)', fallback: 'Not available yet', notes: 'Label from contributor score' },
  { page: 'Activity', section: 'Daily movement chart', element: 'Class 5 min timeline', sourcePaths: ['dailyActivity.class5Min'], transform: 'decodeClass5Min -> level 0..3 -> AxisBarChart', fallback: 'No data in selected range', notes: 'Axes + ticks required' },
  { page: 'Activity', section: 'This week', element: 'Saved activity time', sourcePaths: ['getRange(last7).dailyActivity.mediumActivityTime', 'getRange(last7).dailyActivity.highActivityTime'], transform: 'daily sum -> weekly AxisBarChart', fallback: 'No data in selected range', notes: '7-day compact chart' },
  { page: 'Activity', section: 'Weekly zone minutes', element: 'Zone proxy bars', sourcePaths: ['dailyActivity.sedentaryTime', 'dailyActivity.lowActivityTime', 'dailyActivity.mediumActivityTime', 'dailyActivity.highActivityTime'], transform: 'zone0..zone3 in minutes', fallback: 'Not available in this export', notes: 'Zone4/5 fixed zero unless supported' }
];
