export const readinessUiMapping = [
  { page: 'Readiness', section: 'Score', element: 'Readiness score', sourcePaths: ['dailyReadiness.score'], transform: 'toNumber', fallback: 'Not in this export', notes: 'Selected day' },
  { page: 'Readiness', section: 'Score', element: 'Readiness label', sourcePaths: ['dailyReadiness.score'], transform: 'scoreBand(score)', fallback: 'Not available yet', notes: 'Optimal/Good/Fair/Pay attention' },
  { page: 'Readiness', section: 'Contributors', element: 'Contributor list', sourcePaths: ['dailyReadiness.contributors.resting_heart_rate', 'dailyReadiness.contributors.hrv_balance', 'dailyReadiness.contributors.body_temperature', 'dailyReadiness.contributors.recovery_index', 'dailyReadiness.contributors.previous_night', 'dailyReadiness.contributors.sleep_balance', 'dailyReadiness.contributors.sleep_regularity', 'dailyReadiness.contributors.previous_day_activity', 'dailyReadiness.contributors.activity_balance'], transform: 'scoreBand + rail percentage', fallback: 'Not available yet', notes: 'Null contributor values display explicit placeholder' },
  { page: 'Readiness', section: 'Key metrics', element: 'Resting heart rate', sourcePaths: ['sleepModel.lowestHeartRate'], transform: 'toNumber + bpm', fallback: 'Not available in this export', notes: 'sleepmodel source' },
  { page: 'Readiness', section: 'Key metrics', element: 'HRV', sourcePaths: ['sleepModel.avgHrv'], transform: 'toNumber + ms', fallback: 'Not available in this export', notes: 'sleepmodel source' },
  { page: 'Readiness', section: 'Key metrics', element: 'Body temperature', sourcePaths: ['dailyReadiness.temperatureDeviation'], transform: 'signed toFixed(1)', fallback: 'Not in this export', notes: '°C' },
  { page: 'Readiness', section: 'Key metrics', element: 'Respiratory rate', sourcePaths: ['sleepModel.avgBreath'], transform: 'toNumber + /min', fallback: 'Not available in this export', notes: 'sleepmodel source' },
  { page: 'Readiness', section: 'Details', element: 'Lowest heart rate chart', sourcePaths: ['sleepModel.heart_rate JSON -> sleepHrSeries'], transform: 'axis chart with x/y ticks + labels', fallback: 'No data in selected range', notes: 'Null values preserved as gaps' },
  { page: 'Readiness', section: 'Details', element: 'Average HRV chart', sourcePaths: ['sleepModel.hrv JSON -> sleepHrvSeries'], transform: 'axis chart with x/y ticks + labels', fallback: 'No data in selected range', notes: 'Downsampled deterministically' }
];
