export const sleepUiMapping = [
  { page: 'Sleep', section: 'Score', element: 'Sleep score', sourcePaths: ['dailySleep.score'], transform: 'toNumber', fallback: 'Not in this export', notes: 'Selected day' },
  { page: 'Sleep', section: 'Contributors', element: 'Total sleep', sourcePaths: ['sleepModel.totalSleepSec'], transform: 'seconds -> h/m', fallback: 'Not available in this export', notes: 'Duration from sleepmodel only' },
  { page: 'Sleep', section: 'Contributors', element: 'Efficiency', sourcePaths: ['sleepModel.efficiencyPct'], transform: 'toNumber + %', fallback: 'Not available in this export', notes: 'Rounded integer percent' },
  { page: 'Sleep', section: 'Contributors', element: 'Restfulness + Timing labels', sourcePaths: ['dailySleep.contributors.restfulness', 'dailySleep.contributors.timing'], transform: 'scoreBand + score', fallback: 'Not available yet', notes: 'Score labels only, not duration source' },
  { page: 'Sleep', section: 'Contributors', element: 'Latency', sourcePaths: ['sleepModel.latencySec'], transform: 'seconds -> minutes', fallback: 'Not available in this export', notes: 'Rounded minutes' },
  { page: 'Sleep', section: 'Details', element: 'Awake/REM/Light/Deep durations', sourcePaths: ['sleepModel.awakeSec', 'sleepModel.remSec', 'sleepModel.lightSec', 'sleepModel.deepSec', 'sleepModel.totalSleepSec'], transform: 'duration + percentage', fallback: 'Not available in this export', notes: 'Seconds from sleepmodel fields' },
  { page: 'Sleep', section: 'Breathing', element: 'SpO2 average', sourcePaths: ['dailySpo2.spo2Average'], transform: 'parseSpo2Average', fallback: 'Not in this export', notes: 'Percent' },
  { page: 'Sleep', section: 'Breathing', element: 'Breathing regularity', sourcePaths: ['dailySpo2.breathingDisturbanceIndex'], transform: 'index -> label', fallback: 'Not available yet', notes: 'Regularity explainer' },
  { page: 'Sleep', section: 'Overnight vitals', element: 'Lowest + avg heart rate', sourcePaths: ['sleepModel.lowestHeartRate', 'sleepModel.avgHeartRate'], transform: 'toNumber + bpm', fallback: 'Not available in this export', notes: 'Card metrics' },
  { page: 'Sleep', section: 'Overnight vitals', element: 'Heart rate chart', sourcePaths: ['sleepModel.hrJson'], transform: 'parseSeriesJson + seriesToPoints + AxisLineChart', fallback: 'No data in selected range', notes: 'Nulls preserved as gaps' },
  { page: 'Sleep', section: 'Overnight vitals', element: 'Average HRV + chart', sourcePaths: ['sleepModel.avgHrv', 'sleepModel.hrvJson'], transform: 'ms value + AxisLineChart', fallback: 'No data in selected range', notes: 'Y-axis nice scaling' },
  { page: 'Sleep', section: 'Stage timeline', element: 'Sleep phases', sourcePaths: ['sleepModel.stage30s', 'sleepModel.bedtimeStart', 'sleepModel.awakeSec', 'sleepModel.deepSec', 'sleepModel.lightSec', 'sleepModel.remSec'], transform: 'inferSleepStageDigitMap + decodeStages + SleepStageChart', fallback: 'Not available in this export', notes: 'Per-row inferred mapping to avoid hardcoded digit assumptions' },
  { page: 'Sleep', section: 'Movement', element: 'Movement timeline', sourcePaths: ['sleepModel.movement30s', 'sleepModel.bedtimeStart'], transform: '30s movement series -> AxisBarChart domain 0..4', fallback: 'Not available in this export', notes: 'Axes always visible' }
];
